.TH libretee 1 "8th October 2012" "0.1" "libretee 0.1"
.SH NAME
libretee \- duplicate standard input to standard output and files.
.SH SYNOPSIS
libretee OPTIONS [FILE]...
.SH DESCRIPTION
.B libretee
reads data written to standard input and outputs it to standard output and a list of files.
.SH OPTIONS
.B libretee
does not have any run-time options.
.SH SEE ALSO
tee(1)
.SH BUGS
.B libretee
has no known bugs.
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)